// Downloads the WebAssembly (WASI) build of ShellCheck into `wasm/`.
//
// This runs after bindl but is independent of it and of every BINDL_* variable:
// the `universal` VSIX target sets BINDL_SKIP to omit the native binaries, and
// that target is precisely the one that needs the WebAssembly module.
//
// GO_SHELLCHECK_COMMIT is bumped by the Renovate custom manager in
// renovate.json. WASM_SHA256 and WASM_SIZE describe the artifact at that
// commit, so they have to be updated in the same change; otherwise the
// verification below fails the build.

import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const GO_SHELLCHECK_COMMIT = "24025c1590296bcce8e494624e8c3561740a32a4";
export const WASM_SHA256 =
  "f9d99fa45ae12d5b735425e6a32f6ea3cc550095b1e82ec1b770141470278c20";
export const WASM_SIZE = 7650497;

const WASM_URL = `https://raw.githubusercontent.com/wasilibs/go-shellcheck/${GO_SHELLCHECK_COMMIT}/internal/wasm/shellcheck.wasm`;
const LICENSE_HEADING = "GNU GENERAL PUBLIC LICENSE";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const wasmDir = path.join(repoRoot, "wasm");
const wasmFile = path.join(wasmDir, "shellcheck.wasm");
const licenseFile = path.join(wasmDir, "LICENSE.shellcheck");
const provenanceFile = path.join(wasmDir, "PROVENANCE.md");

function sha256(buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

async function readIfExists(file, encoding) {
  try {
    return await readFile(file, encoding);
  } catch (error) {
    if (error.code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
}

/** The version the native binaries are pinned to is also the version inside the module. */
async function readShellCheckVersion() {
  const config = await readFile(path.join(repoRoot, "bindl.config.ts"), "utf8");
  const match = /^export const version = "(\d+\.\d+\.\d+)";$/m.exec(config);
  if (!match) {
    throw new Error(
      "Could not read the ShellCheck version from bindl.config.ts",
    );
  }
  return match[1];
}

async function download(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `GET ${url} failed: HTTP ${response.status} ${response.statusText}`,
    );
  }
  return Buffer.from(await response.arrayBuffer());
}

async function fetchWasm() {
  const existing = await readIfExists(wasmFile);
  if (existing && sha256(existing) === WASM_SHA256) {
    return;
  }
  if (existing) {
    console.warn(
      "wasm/shellcheck.wasm does not match the pinned sha256, discarding it",
    );
    await rm(wasmFile);
  }

  console.log(`Downloading ${WASM_URL}`);
  const payload = await download(WASM_URL);
  const actualSha256 = sha256(payload);
  if (payload.length !== WASM_SIZE || actualSha256 !== WASM_SHA256) {
    throw new Error(
      [
        `${WASM_URL} does not match the pinned artifact.`,
        `  expected: ${WASM_SIZE} bytes, sha256 ${WASM_SHA256}`,
        `  actual:   ${payload.length} bytes, sha256 ${actualSha256}`,
        "If the pinned commit was updated, update WASM_SHA256 and WASM_SIZE in scripts/fetch-wasm.mjs to match.",
      ].join("\n"),
    );
  }
  await writeFile(wasmFile, payload);
}

async function fetchLicense(version) {
  const existing = await readIfExists(licenseFile, "utf8");
  if (existing?.includes(LICENSE_HEADING)) {
    return;
  }

  const url = `https://raw.githubusercontent.com/koalaman/shellcheck/v${version}/LICENSE`;
  console.log(`Downloading ${url}`);
  const payload = await download(url);
  if (!payload.toString("utf8").includes(LICENSE_HEADING)) {
    throw new Error(`${url} is not the GNU General Public License v3.0`);
  }
  await writeFile(licenseFile, payload);
}

async function writeProvenance(version) {
  const contents = `# Bundled ShellCheck WebAssembly module

\`shellcheck.wasm\` is a WebAssembly (WASI) build of ShellCheck ${version}, the
same version as the native ShellCheck binaries bundled with this extension.
It is compiled from ShellCheck's Haskell sources with the GHC WebAssembly
backend (\`ghc-wasm-meta\`) and redistributed by the
\`wasilibs/go-shellcheck\` project.

- Upstream: <https://github.com/koalaman/shellcheck> (v${version})
- Redistributor: <https://github.com/wasilibs/go-shellcheck>
- Commit: \`${GO_SHELLCHECK_COMMIT}\`
- Source: <${WASM_URL}>
- Size: ${WASM_SIZE} bytes
- sha256: \`${WASM_SHA256}\`

ShellCheck is licensed under the GNU General Public License v3.0, reproduced in
\`LICENSE.shellcheck\`.

This file is generated by \`scripts/fetch-wasm.mjs\`.
`;
  await writeFile(provenanceFile, contents);
}

try {
  const version = await readShellCheckVersion();
  await mkdir(wasmDir, { recursive: true });
  await fetchWasm();
  await fetchLicense(version);
  await writeProvenance(version);
} catch (error) {
  console.error("Failed to fetch the ShellCheck WebAssembly module:");
  console.error(error);
  process.exitCode = 1;
}
